<?xml version="1.0"?>

<robot xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
       xmlns:xacro="http://ros.org/wiki/xacro"
		name="field_robot">




  
	<xacro:property name="wheel_diameter" value="0.15"/>
	<xacro:property name="wheel_depth" value="0.05"/>
	<xacro:property name="wheel_y_pos" value="0.2"/>
	<xacro:property name="wheel_x_pos" value="0.175"/>
	<xacro:property name="box_h" value="0.125"/>
	<xacro:property name="z_offset_" value="${0.5*box_h+0.055}"/>
	<xacro:property name="laser_offset" value="0.24"/>
 	<xacro:macro name="default_inertial" params="mass">
    	<inertial>
      		<mass value="${mass}" />
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
    </inertial>
 	</xacro:macro>

	
	  <material name="blue">
    	<color rgba="0 0 .8 1"/>
  	</material>

  	<material name="black">
    	<color rgba="0 0 0 1"/>
 	 </material>

  	<material name="white">
    	<color rgba="1 1 1 1"/>
  	</material>
	
	<xacro:macro name="wheel" params="prefix h_refl v_refl">

		<link name="${prefix}_wheel">		
			<visual>
				<geometry>
					<cylinder length="${wheel_depth}" radius="${wheel_diameter/2}"/>
				</geometry>
				<material name="black"/>
			</visual>
			<collision>
				<geometry>
					<cylinder length="${wheel_depth}" radius="${wheel_diameter/2}"/>
				</geometry>
			</collision>
			<xacro:default_inertial mass="1"/>
		</link>

		<joint name="${prefix}_wheel_joint" type="continuous">
			<parent link="base_link"/>
			<child link="${prefix}_wheel"/>
			<axis xyz="0 0 1"/>
			<origin rpy="0 1.57 1.57" xyz="${h_refl*wheel_y_pos} ${v_refl*wheel_x_pos+v_refl*0.01} ${z_offset_-0.0275}"/>
		</joint>

		<transmission name="${prefix}_trans">
  			<type>transmission_interface/SimpleTransmission</type>
  			<joint name="${prefix}_wheel_joint">
   			 	<hardwareInterface>VelocityJointInterface</hardwareInterface>
		  	</joint>
 		 	<actuator name="${prefix}_motor">
   			 	<mechanicalReduction>1</mechanicalReduction>
				<hardwareInterface>VelocityJointInterface</hardwareInterface>
  			</actuator>
		</transmission>

    	<gazebo reference="${prefix}_wheel">
      		<mu1 value="200.0"/>
     		<mu2 value="100.0"/>
     		<kp value="10000000.0" />
      		<kd value="1.0" />
      		<material>Gazebo/Grey</material>
    	</gazebo>

	</xacro:macro>
		
	<xacro:macro name="post" params="prefix h_refl v_refl">
		<link name="${prefix}_post">
			<visual>
				<geometry>
					<cylinder length="0.04" radius="0.02"/>
				</geometry>
				<origin rpy="0 0 0" xyz="${h_refl*0.2} ${v_refl*0.1075} ${z_offset_+0.0825}"/>
			</visual>
			<collision>
				<geometry>
					<cylinder length="0.04" radius="0.02"/>
				</geometry>
				<origin rpy="0 0 0" xyz="${h_refl*0.2} ${v_refl*0.1075} ${z_offset_+0.0825}"/>
			</collision>

			<xacro:default_inertial mass="1"/>
		</link>
		<joint name="${prefix}_post_joint" type="fixed">
			<parent link="base_link"/>
			<child link="${prefix}_post"/>
		</joint>
	</xacro:macro>

	<link name ="base_link">
		<visual>
			<geometry>
				<box size="0.6 .3 .125"/>
			</geometry>
			<origin rpy="0 0 0" xyz="0.0 0.0 ${z_offset_}"/>			
		</visual>
		<collision>
			<geometry>
				<box size="0.6 .3 .125"/>
			</geometry>
			<origin rpy="0 0 0" xyz="0.0 0.0 ${z_offset_}"/>
		</collision>	
		<xacro:default_inertial mass="20"/>
	</link>

	<xacro:wheel prefix="left_front" h_refl="1" v_refl="1"/>
	<xacro:wheel prefix="left_back" h_refl="-1" v_refl="1"/>
	<xacro:wheel prefix="right_front" h_refl="1" v_refl="-1"/>
	<xacro:wheel prefix="right_back" h_refl="-1" v_refl="-1"/>

	<xacro:post prefix="left_front" h_refl="1" v_refl="1"/>
	<xacro:post prefix="left_back" h_refl="-1" v_refl="1"/>
	<xacro:post prefix="right_front" h_refl="1" v_refl="-1"/>
	<xacro:post prefix="right_back" h_refl="-1" v_refl="-1"/>
	

	<link name ="top_plate">
		<visual>
			<geometry>
				<box size="0.6 .3 .03"/>
			</geometry>
			<origin rpy="0 0 0" xyz="0 0 ${z_offset_+0.1175}"/>
		</visual>
		<xacro:default_inertial mass="10"/>
	</link>

	<joint name="base_to_top_plate" type="fixed">
		<parent link="base_link"/>
		<child link="top_plate"/>
	</joint>

  <xacro:include filename="$(find sick_tim)/urdf/sick_tim.urdf.xacro" />
	
  <xacro:sick_tim310 name="laser" ros_topic="gazebo/scan"  />

 
      <joint name="laser_base_joint" type="fixed">
      <parent link="base_link" />
      <child link="laser_mount_link" />
      <origin rpy="0 3.14 3.14" xyz="0 0 ${laser_offset}"/>
    </joint>

<gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>/</robotNamespace>
	  <robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType>
    </plugin>
	
  </gazebo>
       

	
</robot>

